// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize logging for the Rust side.
/// Call once from Dart before starting the MCP server.
Future<void> initLogging() => RustLib.instance.api.crateApiInitLogging();

/// Start the MCP server with Dart callbacks for UI operations.
///
/// - `show_form`: Called when the agent requests a form. Receives JSON string
///   with {schema, title, prefill}. Return JSON string with form data, or null if cancelled.
/// - `show_confirm`: Called when the agent requests confirmation. Receives JSON string
///   with {message, title}. Return true if confirmed.
/// - `show_toast`: Called for toast notifications. Receives JSON string
///   with {message, severity}. Fire-and-forget.
/// - `show_output`: Called to display rich output. Receives JSON string
///   with {content, output_type, title}. Return true when dismissed.
/// - `show_page`: Called when the agent requests a page. Receives JSON string
///   with {children, title, prefill}. Return JSON string with input data, or null if cancelled.
///
/// This function blocks until the MCP server shuts down (stdin closes).
Future<void> startMcpServer({
  required FutureOr<String?> Function(String) showForm,
  required FutureOr<bool> Function(String) showConfirm,
  required FutureOr<void> Function(String) showToast,
  required FutureOr<bool> Function(String) showOutput,
  required FutureOr<void> Function(String) onPill,
  required FutureOr<String?> Function(String) showPage,
}) => RustLib.instance.api.crateApiStartMcpServer(
  showForm: showForm,
  showConfirm: showConfirm,
  showToast: showToast,
  showOutput: showOutput,
  onPill: onPill,
  showPage: showPage,
);

/// Get the version of the Niobium MCP server.
Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();
